lawSamples = [
    "Vi phạm tốc độ khi lái xe ô tô bị xử phạt thế nào?",
    "Có được mang hung khí phòng thân khi ra đường không?",
    "Tuổi tối thiểu bị truy cứu trách nhiệm hình sự là bao nhiêu?",
    "Đánh nhau gây thương tích bị phạt bao nhiêu tiền?",
    "Kinh doanh không có giấy phép bị xử lý ra sao?",
    "Xâm phạm riêng tư trên mạng xã hội bị phạt thế nào?",
    "Điều kiện để được cấp giấy phép lái xe hạng C?",
    "Quy định về nồng độ cồn khi lái xe máy?",
    "Tự ý phá khóa điện thoại người khác có bị sao không?",
    "Quy trình tố cáo tội phạm ma túy như thế nào?",
    "Làm giả giấy tờ tùy thân bị phạt bao nhiêu năm tù?",
    "Quy định về giờ giấc hoạt động của quán karaoke?",
    "Xả rác bừa bãi nơi công cộng bị phạt bao nhiêu?",
    "Điều kiện cấp phép xây dựng nhà ở riêng lẻ?",
    "Quấy rối tình dục nơi công cộng bị xử lý thế nào?",
    "Chống người thi hành công vụ bị phạt ra sao?",
    "Quy định về khoảng cách an toàn khi đốt vàng mã?",
    "Tội lừa đảo chiếm đoạt tài sản xử phạt thế nào?",
    "Đi xe máy không đội mũ bảo hiểm phạt bao nhiêu?",
    "Quy định về an ninh trật tự tại khu dân cư?",
    "Có được tổ chức đám cưới đường không?",
    "Xử lý vi phạm về pháo nổ thế nào?",
    "Điều kiện thành lập công ty tư nhân?",
    "Quy định về bảo vệ dữ liệu cá nhân?",
    "Tội phát tán nội dung đồi trụy bị phạt bao nhiêu năm?",
    "Quyền và nghĩa vụ của người tố giác tội phạm?",
    "Xâm phạm danh dự nhân phẩm trên facebook xử lý sao?",
    "Quy định về sử dụng loa đài ở khu dân cư?",
    "Điều kiện ly hôn đơn phương thế nào?",
    "Xử lý hành vi trốn thuế doanh nghiệp?",
    "Quy định về an toàn phòng cháy chữa cháy?",
    "Tội cố ý gây thương tích bị phạt bao nhiêu năm tù?",
    "Quy trình khiếu nại quyết định hành chính?",
    "Đi xe đạp điện có cần bằng lái không?",
    "Quy định về nuôi chó nguy hiểm trong thành phố?",
    "Xử lý hành vi đánh bạc trái phép?",
    "Quyền thừa kế tài sản của con nuôi?",
    "Điều kiện cấp visa lao động cho người nước ngoài?",
    "Quy định về tốc độ xe máy trong ngõ hẹp?",
    "Xử lý vi phạm hành chính trong lĩnh vực y tế?",
    "Quy định về tiếng ồn công trình xây dựng ban đêm?",
    "Tội mua bán hàng cấm bị xử phạt thế nào?",
    "Thủ tục tố cáo hành vi tham nhũng?",
    "Quy định về vũ khí thô sơ tự chế?",
    "Xử lý hành vi chặt cây xanh công cộng?",
    "Quyền sử dụng đất nông nghiệp thế nào?",
    "Điều kiện kinh doanh quán ăn vỉa hè?",
    "Quy định về đăng ký xe máy cũ?",
    "Xử lý hành vi xúc phạm lãnh tụ?",
    "Quy trình giải quyết tranh chấp đất đai?",
    "Tội lạm dụng tín nhiệm chiếm đoạt tài sản?",
    "Quy định về an toàn lao động trên công trường?",
    "Xử lý hành vi buôn lậu qua biên giới?",
    "Quyền của người bị tạm giữ?",
    "Điều kiện cấp phép tổ chức sự kiện đông người?",
    "Quy định về bảo vệ trẻ em trên không gian mạng?",
    "Xử lý hành vi trốn nghĩa vụ quân sự?",
    "Quy trình thành lập hộ kinh doanh cá thể?",
    "Tội cưỡng đoạt tài sản xử lý thế nào?",
    "Quy định về khoảng cách xây nhà với đường sắt?",
    "Xử lý vi phạm trong lĩnh vực bảo vệ môi trường?",
    "Quyền lợi của nạn nhân bạo lực gia đình?",
    "Điều kiện nhập quốc tịch Việt Nam?",
    "Quy định về vận chuyển hàng hóa nguy hiểm?",
    "Xử lý hành vi làm giả tem kiểm định?",
    "Quy trình khiếu kiện hành chính về thuế?",
    "Tội lợi dụng chức vụ trong doanh nghiệp nhà nước?",
    "Quy định về an ninh mạng với doanh nghiệp nước ngoài?",
    "Xử lý hành vi quảng cáo gian dối?",
    "Quyền sở hữu trí tuệ với sản phẩm sáng tạo?",
    "Điều kiện hoạt động của tổ chức phi chính phủ?",
    "Quy định về bảo hiểm y tế bắt buộc?",
    "Xử lý vi phạm trong lĩnh vực giáo dục?",
    "Quy trình giải quyết tranh chấp lao động?",
    "Tội chiếm dụng vốn đầu tư xử lý thế nào?",
    "Quy định về tiêu chuẩn phòng cháy chữa cháy cho chung cư?",
    "Xử lý hành vi sản xuất hàng giả?",
    "Quyền lợi của người tố cáo sai sự thật?",
    "Điều kiện cấp phép khai thác khoáng sản?",
    "Quy định về bảo vệ di sản văn hóa?",
    "Xử lý hành vi xâm phạm bí mật thư tín?",
    "Quy trình thay đổi hộ khẩu thường trú?",
    "Tội rửa tiền bị xử phạt như thế nào?",
    "Quy định về an toàn thực phẩm trong trường học?",
    "Xử lý hành vi lấn chiếm vỉa hè?",
    "Quyền lợi của người lao động khi bị sa thải?",
    "Điều kiện thành lập trường mầm non tư thục?",
    "Quy định về phòng chống dịch bệnh động vật?",
    "Xử lý hành vi trốn thuế thu nhập cá nhân?",
    "Quy trình khiếu nại quyết định thanh tra?",
    "Tội phá hoại tài sản công cộng xử lý thế nào?",
    "Quy định về tiêu chuẩn nước thải công nghiệp?",
    "Xử lý hành vi buôn bán động vật hoang dã?",
    "Quyền của người bị thu hồi đất?",
    "Điều kiện cấp phép vận tải hành khách?",
    "Quy định về an toàn điện trong hộ gia đình?",
    "Xử lý hành vi trốn bảo hiểm xã hội?",
    "Quy trình giải quyết khiếu nại về đấu thầu?",
    "Tội lợi dụng tín nhiệm trong hợp đồng?",
    "Quy định về khoảng cách an toàn đường điện cao thế?",
    "Xử lý hành vi sử dụng chất cấm trong chăn nuôi?",
    "Quyền lợi của người tiêu dùng bị lừa đảo?",
    "Tôi có thể lái xe khi dưới 18 tuổi không?",
    "Luật cư trú là luật gì?",
    "Bạn hãy liệt kê các điều luật mà bạn biết?",
    "Bạn có thể cho tôi biết về Luật Đất đai không?",
    "Bạn có thể cho tôi biết về Luật Hôn nhân và gia đình không?",
    "Điều 1 và điểu 30 khác nhau điểm gì?",
    "Luật nào là luật khắt khe nhất trong pháp điển?",
    "Luật nào là luật dễ vi phạm nhất?",
	"Điều nào trong pháp điển là dài nhất?",
    "Xin chào, tôi có thể hỏi 1 số thông tin về luật được không?",
    "Hi, trẻ em dưới 18 tuổi có được lái xe không?",
    "Bạn có thể cho tôi biết về Luật Lao động không?",
    "Liệu tôi có thể trốn thuế không?",
    "Cho tôi biết ai là người có nghĩa vụ tham gia bảo hiểm xã hội?",
    "Tôi có thể đốt chứng minh nhân dân không?",
    "Bạn có thể mô tả các điều luật của luật cư trú không?",
    "Bạn biết luật nào làm tôi thấy hấp dẫn nhất không?",
    "Bạn có thể cho tôi biết về Luật Đầu tư không?",
    "Điều nào trong Luật Đầu tư là quan trọng nhất?",
	"Cho tôi biết mục nào chi tiết nhất về luật liên quan đến trẻ em."
    "Bạn có thể cho tôi biết về Luật Hình sự không?",
]

chatSamples = [
    "Bạn có hay đi mua sắm không?",
	"Bạn có hay chơi thể thao không, môn nào là yêu thích?",
	"Bạn thích ngày nắng hay ngày mưa hơn?",
	"Bạn thích hoa nào nhất và tại sao?",
	"Bạn nghĩ sống một mình có vui không?",
	"Bạn có hay sử dụng mạng xã hội không?",
	"Bạn thường đi ngủ lúc mấy giờ?",
	"Bạn có kế hoạch gì cho cuối tuần này không?",
	"Bạn nghĩ tuổi trẻ nên trải nghiệm điều gì nhất?",
	"Hôm nay thời tiết thế nào?",
	"Bạn nghĩ người yêu lý tưởng phải như thế nào?",
	"Món phở hay bún bò bạn thích hơn?",
	"Bạn có chơi game không?",
	"Bạn thích đọc sách không? Nếu có thì thể loại nào?",
	"Bạn có thích đi dạo công viên không?",
	"Món quà nào bạn muốn tặng bố mẹ nhất?",
	"Nếu được chọn một nghề tay trái, bạn chọn gì?",
	"Bạn có thích đi xem phim ở rạp không?",
	"Bạn có thích nghe podcast không?",
	"Bạn có xem bộ phim nào hay gần đây không?",
	"Bạn có thích nấu ăn không?",
	"Bạn có thích ngắm hoàng hôn hay bình minh hơn?",
	"Bạn thích ăn món gì nhất?",
    "Bạn là ai?",
    "Hi",
    "Hello"
	"Bạn có thường xuyên đi cà phê không?",
	"Bạn thích đọc sách không? Thể loại sách bạn thích là gì?",
	"Bạn có hay đi tập thể dục không?",
	"Bạn có thích ngắm sao trời không?",
	"Bạn thích uống nước ngọt hay nước lọc hơn?",
	"Nếu được chọn một nơi để thư giãn, bạn chọn đâu?",
	"Bạn có hay nấu ăn ở nhà không?",
	"Bạn đang đọc cuốn sách nào vậy?",
	"Thời tiết hôm nay thế nào?",
	"Bạn thích trà hay cà phê hơn?",
	"Bạn thích kiểu nhà truyền thống hay hiện đại hơn?",
	"Bạn thích đọc sách gì?",
	"Nếu được gặp một người nổi tiếng, bạn chọn ai?",
	"Bạn thích đi ăn buffet hay gọi món riêng hơn?",
	"Bạn thích mặc áo dài hay quần jeans hơn?",
	"Nếu được đi du lịch miễn phí, bạn sẽ chọn nơi nào?",
	"Hôm nay bạn cảm thấy thế nào?",
	"Có lần nào bạn giúp người lạ mà thấy vui không?",
	"Bạn có nuôi thú cưng không?",
	"Bạn thích đọc sách không? Thể loại sách yêu thích của bạn là gì?",
	"Bạn nghĩ người Việt mình có thân thiện với khách nước ngoài không?",
	"Bạn nghĩ gì về công nghệ AI?",
	"Có món ăn nào bạn không thích nhưng vẫn phải ăn không?",
	"Bạn có hay đọc báo không?",
	"Bạn có hay tham gia các hoạt động tình nguyện không?",
	"Bạn có hay đi xem liveshow ca nhạc không?",
	"Bạn có thích xem hài không?",
	"Bạn có thích nuôi thú cưng không, loại nào?",
	"Có thói quen nào bạn muốn bỏ nhưng chưa được không?",
	"Bạn nghĩ sống chậm có khó không?",
	"Có món đồ nào bạn giữ từ lâu vì kỷ niệm không?",
	"Bạn có đọc sách không? Cuốn sách bạn đang đọc là gì?",
	"Món ăn vặt nào bạn hay ăn khi xem phim?",
	"Bạn có hay tham gia hoạt động từ thiện không?",
	"Bạn có thích xem phim Việt Nam hay phim nước ngoài hơn?",
	"Món ăn nào bạn muốn thử từ nước ngoài?",
	"Bạn có thích đi mua sắm không?",
	"Món ăn nào bạn thấy hợp với ngày đông nhất?",
	"Bạn nghĩ người yêu cũ có nên làm bạn không?",
	"Bạn thường làm gì để giảm stress sau một ngày dài?",
	"Bạn có xem tin tức hôm nay không?",
	"Bạn có hay đi hát karaoke không?",
	"Bạn thích đi biển hay lên núi hơn?",
	"Bạn có hay thức khuya không, làm gì lúc đó?",
	"Nếu được chọn một con vật làm bạn, bạn chọn gì?",
	"Bạn nghĩ gì về công việc hiện tại của mình?",
	"Bạn thích không gian yên tĩnh hay náo nhiệt?",
	"Bạn thích nghe podcast hay xem video hơn?",
	"Bạn thường làm gì để giải tỏa căng thẳng?",
	"Có trò chơi nào bạn từng chơi hồi nhỏ không quên được?",
	"Bạn thích nghe nhạc gì khi rảnh rỗi?",
	"Bạn có thích đi picnic không?",
	"Có nơi nào ở Việt Nam bạn muốn khám phá không?",
	"Bộ phim bạn xem gần đây nhất là gì?",
	"Bạn nghĩ người Việt mình có hay nói đùa không?",
	"Bạn có theo dõi tin tức gì đặc biệt gần đây không?",
	"Bạn nghĩ điều gì làm nên hạnh phúc?",
	"Bạn nghĩ gì về thời tiết hôm nay?",
	"Bạn thích đi du lịch ở đâu?",
	"Bạn có thích đi chợ truyền thống hay siêu thị hơn?",
	"Bạn nghĩ ở quê hay thành phố sống thoải mái hơn?",
	"Nếu được quay lại tuổi thơ, bạn muốn làm gì nhất?",
	"Có lần nào bạn đi lạc mà thấy thú vị không?",
	"Bạn thích đi du lịch ở đâu nhất?",
	"Hello",
	"Bạn thích đi du lịch một mình hay đi cùng nhóm?",
	"Bạn có hay nấu ăn không?",
	"Thói quen buổi sáng của bạn là gì?",
	"Có lần nào bạn quên sinh nhật bạn thân không?",
	"Bạn thích thể loại nhạc nào?",
	"Bạn thích đi bộ hay đi xe đạp hơn?",
	"Cuốn sách gần đây nhất bạn đọc là gì?",
	"Điều gì làm bạn cười nhiều nhất trong ngày?",
	"Bạn có hay đi cà phê với bạn bè không?",
	"Món ăn đường phố nào bạn hay ăn nhất?",
	"Bạn nghĩ tình bạn khác tình yêu ở điểm nào?",
	"Bạn có hay xem phim hài để giải trí không?",
	"Có mùi hương nào làm bạn thấy dễ chịu không?",
	"Nếu được sống ở một thành phố khác, bạn chọn đâu?",
	"Chào bạn, hôm nay bạn thế nào?",
	"Xin chào",
	"Bạn nghĩ người Việt mình có gì đặc biệt?",
	"Cuốn sách bạn đang đọc là gì?",
	"Bạn có thích học ngoại ngữ không?",
	"Bạn nghĩ người Việt mình thân thiện không?",
	"Món ăn nào bạn tự tin nấu ngon nhất?",
	"Nếu được chọn một siêu năng lực, bạn muốn có gì?",
	"Món ăn nào bạn thấy ngon nhất ở Việt Nam?",
	"Bạn có hay chơi game không, game nào là yêu thích?",
	"Món ăn yêu thích của bạn là gì?",
	"Bạn có thích chụp ảnh phong cảnh không?",
	"Bạn có thích xem bóng đá không?",
	"Món ăn mẹ nấu nào bạn thấy ngon nhất?",
	"Bạn có hay đi cà phê không?",
	"Món tráng miệng yêu thích của bạn là gì?",
	"Bạn nghĩ điều gì quan trọng nhất trong дружба?",
	"Bạn có thường xuyên đọc tin tức không?",
	"Bạn nghĩ người Việt mình có sáng tạo không?",
	"Nếu được chọn một ngày lễ yêu thích, bạn chọn gì?",
	"Bạn làm nghề gì?",
	"Bạn thích nghe nhạc Việt hay nhạc quốc tế hơn?",
	"Nếu được nghỉ 1 tuần, bạn sẽ làm gì?",
	"Có bài thơ nào bạn thuộc lòng không?",
	"Bạn có hay hát karaoke với bạn bè không?",
	"Có bộ phim nào làm bạn khóc không?",
	"Bạn thích mùa nào nhất trong năm?",
	"Bạn có thích công việc hiện tại của mình không?",
	"Bạn có tin vào bói toán không?",
	"Bạn có hay nghe podcast không?",
	"Bạn có dự định học thêm gì không?",
	"Thời tiết hôm nay đẹp quá nhỉ?",
	"Bạn có hay nghe radio không, chương trình nào?",
	"Bạn thích uống trà sữa hay cà phê sữa hơn?",
	"Bạn thích đi xem phim ở rạp hay xem ở nhà hơn?",
	"Có lần nào bạn bị mất đồ mà tìm lại được không?",
	"Mùa nào trong năm bạn thích nhất và tại sao?",
	"Bạn thích màu sắc nào nhất và tại sao?",
	"Bạn có hay xem livestream trên mạng không?",
	"Bạn thích nghe thể loại nhạc gì?",
	"Có bài hát nào gợi nhớ tuổi thơ của bạn không?",
	"Có lần nào bạn thử làm điều gì mới mẻ không?",
	"Có kỷ niệm nào từ thời đi học làm bạn nhớ mãi không?",
	"Thời gian rảnh bạn hay ở nhà hay ra ngoài chơi?",
	"Bạn nghĩ đi xe máy hay ô tô tiện hơn?",
	"Bạn có học ngoại ngữ nào không?",
	"Bạn có thích tự tay làm đồ handmade không?",
	"Bạn có thích uống cà phê không?",
	"Bạn có hay đi xem phim ở rạp không?",
	"Bạn có thích đi dạo phố không?",
	"Bạn thích kiểu tóc nào cho bản thân?",
	"Bạn có thích trồng cây không?",
	"Bạn nghĩ mạng xã hội nào thú vị nhất hiện nay?",
	"Bạn có sở thích gì đặc biệt không?",
	"Bạn có chơi môn thể thao nào không?",
	"Bạn có hay đọc tin tức không?",
	"Có cuốn sách nào bạn đọc đi đọc lại không chán không?",
	"Bạn có sử dụng mạng xã hội nào không?",
	"Món quà nào bạn từng nhận mà thấy ý nghĩa nhất?",
	"Bạn đã ăn tối chưa?",
	"Bạn đã xem bộ phim nào hay gần đây không?",
	"Bạn có hay viết nhật ký không?",
	"Bạn thích không khí Tết hay Trung Thu hơn?",
	"Bạn nghĩ điều gì làm bạn tự hào về bản thân?",
	"Bạn thích đọc sách thể loại gì?",
	"Bạn nghĩ mưa có lãng mạn như trong phim không?",
	"Cuối tuần này bạn có kế hoạch gì không?",
	"Bạn thích nghe thể loại nhạc nào?"
]