lawSamples = [
    "Ở Việt Nam, hình phạt tối đa cho tội trộm cắp tài sản là gì?",
    "Luật giao thông Việt Nam quy định thế nào về việc uống rượu bia khi lái xe?",
    "Người dưới 18 tuổi có bị đi tù nếu phạm tội không?",
    "Tội đánh người gây thương tích ở Việt Nam bị xử lý ra sao?",
    "Luật Việt Nam có cấm hút thuốc lá ở nơi công cộng không?",
    "Mức phạt khi vượt đèn đỏ ở Việt Nam hiện nay là bao nhiêu?",
    "Tội buôn bán ma túy ở Việt Nam có thể bị tử hình không?",
    "Người nước ngoài vi phạm pháp luật ở Việt Nam sẽ bị xử lý thế nào?",
    "Luật Việt Nam quy định gì về việc mang vũ khí trái phép?",
    "Tội lừa đảo qua mạng ở Việt Nam bị phạt bao nhiêu năm tù?",
    "Quy định về giờ giới nghiêm ở Việt Nam hiện nay có còn không?",
    "Người gây rối trật tự công cộng bị phạt tiền tối đa bao nhiêu?",
    "Luật Việt Nam có cho phép tự vệ khi bị tấn công không?",
    "Tội cố ý gây thương tích có thể bị phạt tù bao lâu?",
    "Mang dao trong người mà không có giấy phép bị xử lý ra sao?",
    "Luật Việt Nam quy định gì về việc sử dụng pháo nổ trong dịp Tết?",
    "Người say rượu gây tai nạn giao thông bị xử phạt thế nào?",
    "Tội bạo hành gia đình ở Việt Nam có hình phạt cụ thể không?",
    "Luật giao thông Việt Nam có bắt buộc đội mũ bảo hiểm không?",
    "Người không chấp hành lệnh của công an sẽ bị xử lý ra sao?",
    "Tội phá hoại tài sản công cộng bị phạt bao nhiêu tiền?",
    "Luật Việt Nam có cấm quay phim cảnh sát đang làm nhiệm vụ không?",
    "Hành vi đua xe trái phép bị xử phạt như thế nào?",
    "Người dưới 16 tuổi lái xe máy bị phạt ra sao?",
    "Tội trốn thuế ở Việt Nam có thể bị tù không?",
    "Luật Việt Nam quy định gì về việc nuôi chó không rọ mõm?",
    "Hành vi xả rác bừa bãi bị phạt bao nhiêu tiền?",
    "Tội cố ý gây cháy rừng ở Việt Nam bị xử lý thế nào?",
    "Luật Việt Nam có quy định gì về việc sử dụng súng săn?",
    "Người vi phạm luật an ninh mạng bị xử phạt ra sao?",
    "Tội tàng trữ chất cấm ở Việt Nam có mức phạt tối đa là gì?",
    "Luật giao thông Việt Nam có cấm nghe điện thoại khi lái xe không?",
    "Hành vi tụ tập đông người trái phép bị xử lý thế nào?",
    "Tội vu khống người khác ở Việt Nam bị phạt bao nhiêu?",
    "Luật Việt Nam quy định gì về việc bán hàng rong ở khu vực cấm?",
    "Người gây tai nạn giao thông rồi bỏ trốn bị xử lý ra sao?",
    "Tội sử dụng giấy tờ giả ở Việt Nam có bị tù không?",
    "Luật Việt Nam có cấm trẻ em lao động nặng không?",
    "Hành vi đe dọa người khác bị xử phạt như thế nào?",
    "Tội tham nhũng ở Việt Nam có thể bị tử hình không?",
    "Luật Việt Nam quy định gì về việc sử dụng drone ở khu vực đông người?",
    "Người không đeo khẩu trang ở nơi công cộng bị phạt bao nhiêu?",
    "Tội phá rối an ninh quốc gia bị xử lý ra sao?",
    "Luật giao thông Việt Nam có quy định tốc độ tối đa trong thành phố không?",
    "Hành vi trộm cắp vặt bị xử phạt thế nào ở Việt Nam?",
    "Tội cố ý phát tán thông tin sai lệch bị xử lý ra sao?",
    "Luật Việt Nam có cấm đánh bạc không?",
    "Người vi phạm luật phòng cháy chữa cháy bị phạt bao nhiêu?",
    "Tội hành hung cảnh sát ở Việt Nam bị xử lý thế nào?",
    "Luật Việt Nam quy định gì về việc sử dụng còi xe inh ỏi?",
    "Hành vi vứt xác động vật ra đường bị xử phạt ra sao?",
    "Tội sử dụng ma túy ở Việt Nam có bị đi tù không?",
    "Luật Việt Nam có quy định gì về việc xây dựng trái phép?",
    "Người không khai báo tạm trú bị xử phạt thế nào?",
    "Tội chống người thi hành công vụ bị phạt bao nhiêu năm?",
    "Luật giao thông Việt Nam có cấm chở quá số người quy định không?",
    "Hành vi đốt pháo hoa trái phép bị xử lý ra sao?",
    "Tội lợi dụng trẻ em để ăn xin bị phạt thế nào?",
    "Luật Việt Nam có quy định gì về việc bảo vệ môi trường?",
    "Người không chấp hành cách ly y tế bị xử phạt ra sao?",
    "Tội phá hoại cơ sở hạ tầng bị xử lý thế nào?",
    "Luật Việt Nam có cấm quay phim ở khu vực quân sự không?",
    "Hành vi sử dụng loa phóng thanh quá giờ bị phạt bao nhiêu?",
    "Tội tổ chức vượt biên trái phép bị xử lý ra sao?",
    "Luật Việt Nam quy định gì về việc bán rượu cho trẻ vị thành niên?",
    "Người gây ồn ào ở khu dân cư bị xử phạt thế nào?",
    "Tội cố ý làm giả giấy tờ bị phạt bao nhiêu năm tù?",
    "Luật giao thông Việt Nam có quy định gì về đèn xe ban đêm?",
    "Hành vi vứt kim tiêm bừa bãi bị xử lý ra sao?",
    "Tội lạm dụng chức quyền ở Việt Nam bị xử phạt thế nào?",
    "Luật Việt Nam có cấm sử dụng điện thoại trong rạp chiếu phim không?",
    "Người vi phạm luật bảo vệ động vật hoang dã bị xử lý ra sao?",
    "Tội cố ý làm hư hỏng tài sản người khác bị phạt bao nhiêu?",
    "Luật Việt Nam quy định gì về việc sử dụng hóa chất cấm?",
    "Hành vi giả danh công an bị xử lý thế nào?",
    "Tội tổ chức biểu tình trái phép bị phạt ra sao?",
    "Luật giao thông Việt Nam có quy định gì về việc chở hàng cồng kềnh?",
    "Người không trả nợ ngân hàng bị xử lý thế nào?",
    "Tội cố ý gây ô nhiễm nguồn nước bị xử phạt ra sao?",
    "Luật Việt Nam có cấm quay phim người khác mà không xin phép không?",
    "Hành vi phá hoại biển báo giao thông bị xử lý thế nào?",
    "Tội sử dụng chất nổ trái phép bị phạt bao nhiêu năm?",
    "Luật Việt Nam quy định gì về việc bán thực phẩm bẩn?",
    "Người vi phạm luật bảo vệ trẻ em bị xử phạt ra sao?",
    "Tội cố ý làm lộ bí mật quốc gia bị xử lý thế nào?",
    "Luật giao thông Việt Nam có quy định gì về việc vượt xe ở đường hẹp?",
    "Hành vi sử dụng chó để tấn công người khác bị xử phạt ra sao?",
    "Tội tổ chức mại dâm ở Việt Nam bị phạt bao nhiêu năm?",
    "Luật Việt Nam có cấm sử dụng thuốc lá điện tử ở nơi công cộng không?",
    "Người không đội mũ bảo hiểm khi đi xe máy bị phạt bao nhiêu?",
    "Tội cố ý làm giả bằng cấp bị xử lý thế nào?",
    "Luật Việt Nam quy định gì về việc sử dụng đèn pha trong thành phố?",
    "Hành vi xâm phạm mồ mả bị xử phạt ra sao?",
    "Tội lợi dụng tín ngưỡng để trục lợi bị xử lý thế nào?",
    "Luật Việt Nam có quy định gì về việc bảo vệ dữ liệu cá nhân?",
    "Người không chấp hành kiểm tra nồng độ cồn bị xử phạt ra sao?",
    "Tội cố ý phá hoại di sản văn hóa bị xử lý thế nào?",
    "Luật giao thông Việt Nam có cấm dừng xe trên cầu không?",
    "Hành vi sử dụng chất kích thích trong trường học bị xử phạt ra sao?"
]

chatSamples = [
    "Hello",
    "Xin chào",
    "Chào bạn, hôm nay bạn thế nào?",
    "Bạn thích nghe nhạc gì khi rảnh rỗi?",
    "Món ăn nào bạn thấy ngon nhất ở Việt Nam?",
    "Bạn thường làm gì để giảm stress sau một ngày dài?",
    "Nếu được đi du lịch miễn phí, bạn sẽ chọn nơi nào?",
    "Bạn có thích xem phim Việt Nam hay phim nước ngoài hơn?",
    "Thói quen buổi sáng của bạn là gì?",
    "Bạn nghĩ mạng xã hội nào thú vị nhất hiện nay?",
    "Có kỷ niệm nào từ thời đi học làm bạn nhớ mãi không?",
    "Bạn thích trà hay cà phê hơn?",
    "Nếu được chọn một siêu năng lực, bạn muốn có gì?",
    "Bạn có hay nấu ăn ở nhà không?",
    "Mùa nào trong năm bạn thích nhất và tại sao?",
    "Bạn nghĩ người Việt mình thân thiện không?",
    "Có cuốn sách nào bạn đọc đi đọc lại không chán không?",
    "Bạn thích đi biển hay lên núi hơn?",
    "Món quà nào bạn từng nhận mà thấy ý nghĩa nhất?",
    "Bạn có hay chơi thể thao không, môn nào là yêu thích?",
    "Nếu được quay lại tuổi thơ, bạn muốn làm gì nhất?",
    "Bạn nghĩ điều gì quan trọng nhất trong дружба?",
    "Có bộ phim nào làm bạn khóc không?",
    "Bạn thích mặc áo dài hay quần jeans hơn?",
    "Thời gian rảnh bạn hay ở nhà hay ra ngoài chơi?",
    "Bạn có tin vào bói toán không?",
    "Món ăn vặt nào bạn hay ăn khi xem phim?",
    "Bạn thích không khí Tết hay Trung Thu hơn?",
    "Có bài hát nào gợi nhớ tuổi thơ của bạn không?",
    "Bạn nghĩ ở quê hay thành phố sống thoải mái hơn?",
    "Bạn có thích nuôi thú cưng không, loại nào?",
    "Điều gì làm bạn cười nhiều nhất trong ngày?",
    "Bạn thích đi xem phim ở rạp hay xem ở nhà hơn?",
    "Có nơi nào ở Việt Nam bạn muốn khám phá không?",
    "Bạn nghĩ mưa có lãng mạn như trong phim không?",
    "Món tráng miệng yêu thích của bạn là gì?",
    "Bạn có hay đi cà phê với bạn bè không?",
    "Nếu được gặp một người nổi tiếng, bạn chọn ai?",
    "Bạn thích màu sắc nào nhất và tại sao?",
    "Có thói quen nào bạn muốn bỏ nhưng chưa được không?",
    "Bạn nghĩ người yêu lý tưởng phải như thế nào?",
    "Bạn có thích chụp ảnh phong cảnh không?",
    "Món ăn mẹ nấu nào bạn thấy ngon nhất?",
    "Bạn thích đi bộ hay đi xe đạp hơn?",
    "Có mùi hương nào làm bạn thấy dễ chịu không?",
    "Bạn nghĩ tuổi trẻ nên trải nghiệm điều gì nhất?",
    "Bạn có hay hát karaoke với bạn bè không?",
    "Nếu được nghỉ 1 tuần, bạn sẽ làm gì?",
    "Bạn thích kiểu tóc nào cho bản thân?",
    "Có món đồ nào bạn giữ từ lâu vì kỷ niệm không?",
    "Bạn nghĩ sống một mình có vui không?",
    "Bạn thích uống nước ngọt hay nước lọc hơn?",
    "Có trò chơi nào bạn từng chơi hồi nhỏ không quên được?",
    "Bạn có hay xem livestream trên mạng không?",
    "Món phở hay bún bò bạn thích hơn?",
    "Bạn nghĩ người Việt mình có gì đặc biệt?",
    "Bạn thích nghe podcast hay xem video hơn?",
    "Có lần nào bạn đi lạc mà thấy thú vị không?",
    "Bạn có thích tự tay làm đồ handmade không?",
    "Món ăn đường phố nào bạn hay ăn nhất?",
    "Bạn nghĩ tình bạn khác tình yêu ở điểm nào?",
    "Bạn có hay thức khuya không, làm gì lúc đó?",
    "Nếu được chọn một nghề tay trái, bạn chọn gì?",
    "Bạn thích không gian yên tĩnh hay náo nhiệt?",
    "Có bài thơ nào bạn thuộc lòng không?",
    "Bạn nghĩ đi xe máy hay ô tô tiện hơn?",
    "Bạn có thích ngắm hoàng hôn hay bình minh hơn?",
    "Món ăn nào bạn muốn thử từ nước ngoài?",
    "Bạn nghĩ điều gì làm nên hạnh phúc?",
    "Bạn có hay chơi game không, game nào là yêu thích?",
    "Nếu được sống ở một thành phố khác, bạn chọn đâu?",
    "Bạn thích uống trà sữa hay cà phê sữa hơn?",
    "Có lần nào bạn giúp người lạ mà thấy vui không?",
    "Bạn nghĩ người Việt mình có hay nói đùa không?",
    "Bạn có thích đi chợ truyền thống hay siêu thị hơn?",
    "Món ăn nào bạn tự tin nấu ngon nhất?",
    "Bạn thích ngày nắng hay ngày mưa hơn?",
    "Có lần nào bạn quên sinh nhật bạn thân không?",
    "Bạn nghĩ người yêu cũ có nên làm bạn không?",
    "Bạn có hay xem phim hài để giải trí không?",
    "Nếu được chọn một con vật làm bạn, bạn chọn gì?",
    "Bạn thích đi du lịch một mình hay đi cùng nhóm?",
    "Bạn có hay viết nhật ký không?",
    "Món quà nào bạn muốn tặng bố mẹ nhất?",
    "Bạn nghĩ người Việt mình có sáng tạo không?",
    "Bạn thích hoa nào nhất và tại sao?",
    "Có lần nào bạn thử làm điều gì mới mẻ không?",
    "Bạn có hay nghe radio không, chương trình nào?",
    "Bạn nghĩ sống chậm có khó không?",
    "Bạn thích kiểu nhà truyền thống hay hiện đại hơn?",
    "Có món ăn nào bạn không thích nhưng vẫn phải ăn không?",
    "Bạn có hay đi xem liveshow ca nhạc không?",
    "Nếu được chọn một ngày lễ yêu thích, bạn chọn gì?",
    "Bạn nghĩ người Việt mình có thân thiện với khách nước ngoài không?",
    "Bạn thích đi ăn buffet hay gọi món riêng hơn?",
    "Có lần nào bạn bị mất đồ mà tìm lại được không?",
    "Bạn có thích ngắm sao trời không?",
    "Món ăn nào bạn thấy hợp với ngày đông nhất?",
    "Bạn nghĩ điều gì làm bạn tự hào về bản thân?",
    "Bạn có hay tham gia hoạt động từ thiện không?",
    "Bạn thích nghe nhạc Việt hay nhạc quốc tế hơn?",
    "Nếu được chọn một nơi để thư giãn, bạn chọn đâu?"
]